@echo off
echo Executando testes...
call npm run test
echo.
echo Aguardando 2 segundos...
timeout /t 2 /nobreak > nul
echo Abrindo pasta de relatorios...
start "" ".\reports"
echo Aguardando 2 segundos...
timeout /t 2 /nobreak > nul
echo Abrindo relatorio HTML...
start "" ".\reports\test-report.html"
echo Concluido!
